services:
    px4-msgs:
        image: px4-msgs
        build:
            context: .
            dockerfile: Dockerfile
            args:
              - DOCKER_BUILDKIT=1
        container_name: px4-msgs-cnt
        tty: true
        stdin_open: true
        privileged: true
        network_mode: host
        working_dir: /root/ros2_ws
        volumes:
            - $XAUTHORITY:$XAUTHORITY
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - /etc/sudoers.d:/etc/sudoers.d:ro
            - /dev:/dev
            - $PWD/..:/root/ros2_ws/src/px4_msgs
        environment:
            - DISPLAY=$DISPLAY
            - QT_X11_NO_MITSHM=1
            - XAUTHORITY=$XAUTHORITY
        security_opt:
            - seccomp:unconfined